import TwoBounce
import WaveDynamics

/-!
# PeriodSpectrum: the gcd law, the dihedral factorisation, and the twelve-carrier

Promoted from the experimental `Frequencies` and `Overtones` probes.
On a finite carrier the honest surrogate for frequency is order: the
k-th harmonic is the shift by k, its frequency is the least period,
and order ratios stand in for frequency ratios.

* **The general gcd law** (`order_eq_div_gcd`): on `Fin n` the order
  of `shift k` is `n / gcd n k`. The displacement formula
  (`iterN_shift_val`) reduces the fixed-point condition to
  divisibility of the total displacement by the carrier size
  (`iterN_shift_eq_self_iff`); the return half is gcd cancellation
  (`shift_order_returns`) and the minimality half is Euclid's lemma on
  the coprime quotients (`shift_order_minimal`). The edge `k = 0` is
  an instance: `gcd n 0 = n` gives order one and the shift is the
  identity.
* **The closed-form rotation factorisation** (`rot_eq_two_flips`,
  `rotFactor`): on every `Fin n`, rotation by `k` is the mirror
  through `0` followed by the mirror through `k`, both involutions,
  packaged as the computable `rotFactor k : TwoBounceFactor (rot k)`.
  The generating pair is given by closed arithmetic mirrors; the
  corpus's `factor_fin` obtains a pair for arbitrary injections by
  orbit traversal instead.
* **Overtone generation** (`overtone_generation`): every injective
  endomap on a finite carrier is a composite of two involutions via
  the corpus's own `factor_fin`, so every finite period above the
  fundamental is generated by a pair of flips.
* **The twelve-carrier exhibits** (`interval_addition`,
  `harmonics_are_iterates`, `orders_twelve`, `circle_of_fifths`):
  on the chromatic circle the classical facts are decidable instances
  of the general law. Composition of intervals adds shifts, the
  whole tone has order 6, the major third order 3, the tritone
  order 2, and the circle of fifths closes after twelve steps and at
  no positive step before.

All order-law statements are pointwise on carrier elements; no
function extensionality is used in them. The twelve-carrier exhibits
are decided by the kernel and carry propext and `Quot.sound` through
the `Decidable` instances.

The quarantined remainder of the probes (the concrete `Fin 3` and
`Fin 5` exhibits, the generation fact `fifth_generates`, and the
twelve-carrier instances of the general law) stays in
`formal/experimental/Frequencies.lean` and
`formal/experimental/Overtones.lean`.
-/
namespace Bridge.PeriodSpectrum

open Bridge.TwoBounce (TwoBounceFactor IsInvolution EndoInj factor_fin)

/-- Shift by `k`: the `k`-th harmonic on the carrier `Fin n`. -/
def shift {n : Nat} (k : Fin n) : Fin n → Fin n := fun i => i + k

/-- The iterate, reused from the dynamics layer: this name is a
    transparent alias of `Bridge.WaveDynamics.iterN`, so the bridge
    carries a single iterate definition. -/
abbrev iterN {α : Type} (f : α → α) : Nat → α → α :=
  Bridge.WaveDynamics.iterN f

/-! ## The twelve-carrier -/

/-- The fundamental step on the chromatic circle. -/
def semitone : Fin 12 → Fin 12 := shift 1

/-- The fifth. -/
def fifth : Fin 12 → Fin 12 := shift 7

/-- Interval composition adds shifts: shift arithmetic on the
    twelve-carrier, decidably. -/
theorem interval_addition :
    ∀ (j k : Fin 12) (i : Fin 12),
      shift j (shift k i) = shift (k + j) i := by
  decide

/-- Every harmonic is an iterate of the fundamental: the k-th overtone
    is k beats of the semitone. -/
theorem harmonics_are_iterates :
    ∀ (k : Fin 12) (i : Fin 12),
      iterN semitone k.val i = shift k i := by
  decide

/-- Return checks on the twelve-carrier: the whole tone returns at 6,
    the minor third at 4, the major third at 3, the tritone at 2, the
    semitone and the fifth at 12. Return half only; that these counts
    are the exact orders (minimality) is an instance of the general
    law (`order_eq_div_gcd`). -/
theorem orders_twelve :
    (∀ i, iterN (shift (2 : Fin 12)) 6 i = i) ∧
    (∀ i, iterN (shift (3 : Fin 12)) 4 i = i) ∧
    (∀ i, iterN (shift (4 : Fin 12)) 3 i = i) ∧
    (∀ i, iterN (shift (6 : Fin 12)) 2 i = i) ∧
    (∀ i, iterN semitone 12 i = i) ∧
    (∀ i, iterN fifth 12 i = i) := by
  decide

/-- The circle of fifths closes after twelve steps and at no positive
    step before: the fifth is a generator, so its order is twelve and
    its shift is seven. -/
theorem circle_of_fifths :
    (∀ i, iterN fifth 12 i = i) ∧
    (∀ k : Fin 12, k.val ≠ 0 → ∃ i, iterN fifth k.val i ≠ i) := by
  decide

/-! ## The general gcd law -/

/-- Head-first unfolding of the iterate: one application peels off on
    the outside. `iterN` folds head-first by definition; this is the
    tail-first equation. -/
theorem iterN_succ {α : Type} (f : α → α) :
    ∀ (m : Nat) (a : α), iterN f (m + 1) a = f (iterN f m a) := by
  intro m
  induction m with
  | zero => intro a; rfl
  | succ p ih => intro a; exact ih (f a)

/-- Value of a shift: addition modulo the carrier size. -/
theorem shift_val {n : Nat} (k i : Fin n) :
    (shift k i).val = (i.val + k.val) % n :=
  Fin.val_add i k

/-- Displacement formula: `m` beats of the `k`-th harmonic land at
    `(i + m·k) mod n`. -/
theorem iterN_shift_val {n : Nat} (k : Fin n) (m : Nat) (i : Fin n) :
    (iterN (shift k) m i).val = (i.val + m * k.val) % n := by
  induction m with
  | zero =>
    show i.val = (i.val + 0 * k.val) % n
    rw [Nat.zero_mul, Nat.add_zero, Nat.mod_eq_of_lt i.isLt]
  | succ p ih =>
    rw [iterN_succ, shift_val, ih, Nat.mod_add_mod, Nat.add_mul,
      Nat.one_mul, ← Nat.add_assoc]

/-- Adding `s` fixes a reduced residue `i < n` modulo `n` exactly when
    `s` vanishes modulo `n`. -/
private theorem add_mod_eq_self_iff {n i s : Nat} (hi : i < n) :
    (i + s) % n = i ↔ s % n = 0 := by
  have hn : 0 < n := Nat.lt_of_le_of_lt (Nat.zero_le i) hi
  constructor
  · intro h
    rw [Nat.add_mod, Nat.mod_eq_of_lt hi] at h
    have hr : s % n < n := Nat.mod_lt s hn
    revert h hr
    generalize s % n = r
    intro h hr
    cases Nat.lt_or_ge (i + r) n with
    | inl hlt =>
      rw [Nat.mod_eq_of_lt hlt] at h
      omega
    | inr hge =>
      have hlt2 : i + r - n < n := by omega
      rw [Nat.mod_eq_sub_mod hge, Nat.mod_eq_of_lt hlt2] at h
      omega
  · intro h
    rw [Nat.add_mod, h, Nat.add_zero, Nat.mod_eq_of_lt hi]
    exact Nat.mod_eq_of_lt hi

/-- Euclid step: if `n` divides `m * k`, the coprime part `n / gcd n k`
    divides `m`. The gcd is cancelled on both sides and Euclid's lemma
    applies to the coprime quotients. -/
private theorem div_gcd_dvd_of_dvd_mul {n k m : Nat} (hn : 0 < n)
    (h : n ∣ m * k) : n / Nat.gcd n k ∣ m := by
  have hg : 0 < Nat.gcd n k := Nat.gcd_pos_of_pos_left k hn
  have hgn : Nat.gcd n k ∣ n := Nat.gcd_dvd_left n k
  have hgk : Nat.gcd n k ∣ k := Nat.gcd_dvd_right n k
  have hco : Nat.Coprime (n / Nat.gcd n k) (k / Nat.gcd n k) :=
    Nat.coprime_div_gcd_div_gcd hg
  have h1 : Nat.gcd n k * (m * (k / Nat.gcd n k)) = m * k := by
    rw [Nat.mul_left_comm, Nat.mul_div_cancel' hgk]
  have h2 : Nat.gcd n k * (n / Nat.gcd n k) ∣
      Nat.gcd n k * (m * (k / Nat.gcd n k)) := by
    rw [Nat.mul_div_cancel' hgn, h1]
    exact h
  exact hco.dvd_of_dvd_mul_right ((Nat.mul_dvd_mul_iff_left hg).mp h2)

/-- A shift iterate fixes a point exactly when the carrier size divides
    the total displacement; the criterion is uniform in the point. -/
theorem iterN_shift_eq_self_iff {n : Nat} (k : Fin n) (m : Nat)
    (i : Fin n) :
    iterN (shift k) m i = i ↔ n ∣ m * k.val := by
  rw [← Fin.val_inj, iterN_shift_val]
  exact (add_mod_eq_self_iff i.isLt).trans Nat.dvd_iff_mod_eq_zero.symm

/-- The claimed order is positive: the gcd divides `n`, so the quotient
    is at least one. -/
theorem shift_order_pos {n : Nat} (k : Fin n) :
    0 < n / Nat.gcd n k.val :=
  Nat.div_pos (Nat.le_of_dvd k.pos (Nat.gcd_dvd_left n k.val))
    (Nat.gcd_pos_of_pos_left k.val k.pos)

/-- Return half of the gcd law: `n / gcd n k` beats of the `k`-th
    harmonic return every point, since `(n / gcd n k) · k` is the
    multiple `n · (k / gcd n k)` of the carrier size. -/
theorem shift_order_returns {n : Nat} (k : Fin n) (i : Fin n) :
    iterN (shift k) (n / Nat.gcd n k.val) i = i := by
  apply (iterN_shift_eq_self_iff k _ i).mpr
  have hgn : Nat.gcd n k.val ∣ n := Nat.gcd_dvd_left n k.val
  have hgk : Nat.gcd n k.val ∣ k.val := Nat.gcd_dvd_right n k.val
  have h1 : n / Nat.gcd n k.val * Nat.gcd n k.val *
      (k.val / Nat.gcd n k.val) = n / Nat.gcd n k.val * k.val := by
    rw [Nat.mul_assoc, Nat.mul_div_cancel' hgk]
  rw [← h1, Nat.div_mul_cancel hgn]
  exact Nat.dvd_mul_right n _

/-- Minimality half of the gcd law: below `n / gcd n k` no positive
    beat count fixes any point. A fixed point would force
    `n ∣ m · k`, hence `n / gcd n k ∣ m` by Euclid, hence
    `n / gcd n k ≤ m`. -/
theorem shift_order_minimal {n : Nat} (k : Fin n) {m : Nat}
    (hm : 0 < m) (hlt : m < n / Nat.gcd n k.val) (i : Fin n) :
    iterN (shift k) m i ≠ i := by
  intro h
  have hdvd : n ∣ m * k.val := (iterN_shift_eq_self_iff k m i).mp h
  have hle : n / Nat.gcd n k.val ≤ m :=
    Nat.le_of_dvd hm (div_gcd_dvd_of_dvd_mul k.pos hdvd)
  omega

/-- The gcd law on any finite carrier: the order of `shift k` on
    `Fin n` is `n / gcd n k`. The candidate period is positive, it
    returns every point, and no smaller positive beat count fixes any
    point. -/
theorem order_eq_div_gcd {n : Nat} (k : Fin n) :
    0 < n / Nat.gcd n k.val ∧
    (∀ i, iterN (shift k) (n / Nat.gcd n k.val) i = i) ∧
    (∀ m, 0 < m → m < n / Nat.gcd n k.val →
      ∀ i, iterN (shift k) m i ≠ i) :=
  ⟨shift_order_pos k, shift_order_returns k,
    fun _m hm hlt i => shift_order_minimal k hm hlt i⟩

/-! ## Overtone generation -/

/-- Every injective endomap on a finite carrier, in particular every
    n-cycle, is a composite of two involutions: the whole finite
    period spectrum lies exactly two flips above the fundamental. -/
theorem overtone_generation {n : Nat} (U : Fin n → Fin n)
    (h : EndoInj U) :
    ∃ φ σ : Fin n → Fin n,
      IsInvolution φ ∧ IsInvolution σ ∧ ∀ x, U x = σ (φ x) :=
  let F := factor_fin U h
  ⟨F.φ, F.σ, F.φ_inv, F.σ_inv, F.factor⟩

/-! ## The general dihedral factorisation

Closed form for every rotation on every finite carrier: `rot k` is
`reflAt k ∘ reflZero`, two explicit involutions. All identities are
proved at the `.val` level via `Fin.ext`; the `n = 0` cases are
vacuous since `Fin 0` is empty. -/

/-- Rotation by `k` on `Fin n`, the general overtone step: a
    transparent alias of `shift k`, named for the dihedral reading,
    so the bridge carries a single rotation definition. -/
abbrev rot {n : Nat} (k : Fin n) : Fin n → Fin n := shift k

/-- Mirror through `0` on `Fin n` (negation). -/
def reflZero {n : Nat} : Fin n → Fin n := fun i => -i

/-- Mirror through the `k`-axis on `Fin n`: `i ↦ k - i`. -/
def reflAt {n : Nat} (k : Fin n) : Fin n → Fin n := fun i => k - i

/-- Value of negation on `Fin n`: `(-i).val = (n - i.val) % n`. -/
private theorem neg_val {n : Nat} (i : Fin n) :
    (-i).val = (n - i.val) % n := by
  rw [Fin.neg_def]

/-- `Nat` core of `reflZero_involution`: double reflection through
    `0` modulo `n` is the identity on `{0, …, n-1}`. -/
private theorem neg_neg_val (n a : Nat) (ha : a < n) :
    (n - (n - a) % n) % n = a := by
  cases Nat.eq_zero_or_pos a with
  | inl h0 =>
    subst h0
    rw [Nat.sub_zero, Nat.mod_self, Nat.sub_zero, Nat.mod_self]
  | inr hpos =>
    have h1 : (n - a) % n = n - a := Nat.mod_eq_of_lt (by omega)
    rw [h1]
    have h2 : n - (n - a) = a := by omega
    rw [h2]
    exact Nat.mod_eq_of_lt ha

/-- `Nat` core of `reflAt_involution`: double reflection through the
    `b`-axis modulo `n` is the identity on `{0, …, n-1}`. -/
private theorem sub_sub_val (n a b : Nat) (ha : a < n) (hb : b < n) :
    (n - (n - a + b) % n + b) % n = a := by
  cases Nat.lt_or_ge b a with
  | inl hba =>
    have h1 : (n - a + b) % n = n - a + b := Nat.mod_eq_of_lt (by omega)
    rw [h1]
    have h2 : n - (n - a + b) + b = a := by omega
    rw [h2]
    exact Nat.mod_eq_of_lt ha
  | inr hab =>
    have h1 : n - a + b = b - a + n := by omega
    rw [h1, Nat.add_mod_right]
    have h2 : (b - a) % n = b - a := Nat.mod_eq_of_lt (by omega)
    rw [h2]
    have h3 : n - (b - a) + b = a + n := by omega
    rw [h3, Nat.add_mod_right]
    exact Nat.mod_eq_of_lt ha

/-- `Nat` core of the dihedral identity: reflect through `0`, reflect
    through `b`, and the net effect is addition of `b` modulo `n`. -/
private theorem dihedral_val (n a b : Nat) (ha : a < n) :
    (n - (n - a) % n + b) % n = (a + b) % n := by
  cases Nat.eq_zero_or_pos a with
  | inl h0 =>
    subst h0
    rw [Nat.sub_zero, Nat.mod_self, Nat.sub_zero, Nat.zero_add]
    exact Nat.add_mod_left n b
  | inr hpos =>
    have h1 : (n - a) % n = n - a := Nat.mod_eq_of_lt (by omega)
    rw [h1]
    have h2 : n - (n - a) = a := by omega
    rw [h2]

/-- The zero-axis mirror is an involution on every finite carrier. -/
theorem reflZero_involution {n : Nat} :
    IsInvolution (reflZero (n := n)) := by
  intro i
  apply Fin.ext
  show (-(-i)).val = i.val
  rw [neg_val, neg_val]
  exact neg_neg_val n i.val i.isLt

/-- The `k`-axis mirror is an involution for every `k` and `n`. -/
theorem reflAt_involution {n : Nat} (k : Fin n) :
    IsInvolution (reflAt k) := by
  intro i
  apply Fin.ext
  show (k - (k - i)).val = i.val
  rw [Fin.val_sub, Fin.val_sub]
  exact sub_sub_val n i.val k.val i.isLt k.isLt

/-- **The dihedral identity in closed form.** On every `Fin n`,
    rotation by `k` is the mirror through `0` followed by the mirror
    through `k`: `i + k = k - (-i)`, pointwise. -/
theorem rot_eq_two_flips {n : Nat} (k : Fin n) :
    ∀ i, rot k i = reflAt k (reflZero i) := by
  intro i
  apply Fin.ext
  show (i + k).val = (k - (-i)).val
  rw [Fin.val_add, Fin.val_sub, neg_val]
  exact (dihedral_val n i.val k.val i.isLt).symm

/-- Fully explicit two-bounce factorisation of the rotation by `k`
    on `Fin n`. Contrast with the corpus's `factor_fin`, which is
    also computable but constructs its involution pair by orbit
    traversal for arbitrary injections: here the pair is given by
    closed-form arithmetic mirrors (`reflZero`, `reflAt k`) for
    every rotation on every finite carrier. -/
def rotFactor {n : Nat} (k : Fin n) : TwoBounceFactor (rot k) where
  φ := reflZero
  σ := reflAt k
  φ_inv := reflZero_involution
  σ_inv := reflAt_involution k
  factor := rot_eq_two_flips k

#print axioms Bridge.PeriodSpectrum.interval_addition
#print axioms Bridge.PeriodSpectrum.harmonics_are_iterates
#print axioms Bridge.PeriodSpectrum.orders_twelve
#print axioms Bridge.PeriodSpectrum.circle_of_fifths
#print axioms Bridge.PeriodSpectrum.iterN_succ
#print axioms Bridge.PeriodSpectrum.shift_val
#print axioms Bridge.PeriodSpectrum.iterN_shift_val
#print axioms Bridge.PeriodSpectrum.add_mod_eq_self_iff
#print axioms Bridge.PeriodSpectrum.div_gcd_dvd_of_dvd_mul
#print axioms Bridge.PeriodSpectrum.iterN_shift_eq_self_iff
#print axioms Bridge.PeriodSpectrum.shift_order_pos
#print axioms Bridge.PeriodSpectrum.shift_order_returns
#print axioms Bridge.PeriodSpectrum.shift_order_minimal
#print axioms Bridge.PeriodSpectrum.order_eq_div_gcd
#print axioms Bridge.PeriodSpectrum.overtone_generation
#print axioms Bridge.PeriodSpectrum.neg_val
#print axioms Bridge.PeriodSpectrum.neg_neg_val
#print axioms Bridge.PeriodSpectrum.sub_sub_val
#print axioms Bridge.PeriodSpectrum.dihedral_val
#print axioms Bridge.PeriodSpectrum.reflZero_involution
#print axioms Bridge.PeriodSpectrum.reflAt_involution
#print axioms Bridge.PeriodSpectrum.rot_eq_two_flips
#print axioms Bridge.PeriodSpectrum.rotFactor

end Bridge.PeriodSpectrum
