import Canon
import Ladder
import Limit

/-!
# SpineFacts — what the spine does and does not supply for a Hilbert target

Negative and positive facts about the spine, established here so that any
proposed additional axiom can be checked for independence against them. Nothing
in this module claims, or moves towards, Hilbert-space structure; it fixes the
starting position.

* **Asymmetry** (`rep_not_symmetric`, `rep_zero_is_first_projection`): the
  level-0 reading is the first projection, so the spine's reading is not a
  symmetric form and cannot itself serve as an inner product.
* **No square root** (`no_sqrt_on_fundamental`): the fundamental act has no
  square root among endomaps of its own carrier. A square root of an involution
  satisfies `J⁴ = id` (`sqrt_fourth_power_is_id`).
* **An infinite carrier** (`omega_stage_injective`): the colimit carrier
  `Limit.LevelOmega` contains a copy of `Nat`. Whether any other spine carrier
  is infinite is not decided here, and `level_card_succ` says only that each
  rung gains an element, not that the rungs are finite.
* **Two-valued determinacy** (`reading_is_total_two_valued`): every level
  assigns a definite Bool to every ordered pair. Recorded because this is the
  classical assumption a quantum axiom has to displace.
-/
namespace Quantum.SpineFacts

/-! ## The reading is not a symmetric form -/

/-- The level-0 reading is the first projection (definitional). -/
theorem rep_zero_is_first_projection (x y : Ladder.Level 0) :
    Ladder.rep 0 x y = x := rfl

/-- The spine's reading is not symmetric: swapping arguments changes the
    value already at level 0. An inner product is symmetric (up to the
    involution of the scalars), so `Ladder.rep` is not one. -/
theorem rep_not_symmetric :
    ∃ x y : Ladder.Level 0, Ladder.rep 0 x y ≠ Ladder.rep 0 y x :=
  ⟨true, false, by decide⟩

/-- Asymmetry persists at every level: the lifted pair from level 0 keeps its
    reading (`Ladder.lift_conservative`), so no level's reading is symmetric. -/
theorem rep_not_symmetric_at (k : Nat) :
    ∃ x y : Ladder.Level (0 + k),
      Ladder.rep (0 + k) x y ≠ Ladder.rep (0 + k) y x := by
  refine ⟨Ladder.lift 0 k true, Ladder.lift 0 k false, ?_⟩
  rw [Ladder.lift_conservative 0 k true false,
      Ladder.lift_conservative 0 k false true]
  decide

/-! ## The fundamental act has no square root -/

/-- There is no `J` on the fundamental carrier with `J ∘ J = act`. Proved by
    exhausting the four endomaps of `Bool`; compare
    `Density.boolEndo_complete`. -/
theorem no_sqrt_on_fundamental :
    ¬ ∃ J : Bool → Bool, ∀ b, J (J b) = Canon.theFundamental b := by
  intro ⟨J, hJ⟩
  have h0 : J (J false) = true := hJ false
  have h1 : J (J true) = false := hJ true
  cases hf : J false with
  | false =>
    rw [hf] at h0
    exact Bool.noConfusion (hf.symm.trans h0)
  | true =>
    rw [hf] at h0
    cases ht : J true with
    | false => exact Bool.noConfusion (ht.symm.trans h0)
    | true =>
      rw [ht] at h1
      exact Bool.noConfusion (ht.symm.trans h1)

/-- A square root of an involutive act satisfies `J⁴ = id`, so its order
    *divides* four. This is the algebraic signature of a complex structure:
    `act` plays the role of `-1`, so `J` plays the role of `i`. The order is
    exactly four only under further hypotheses — with `act = id` and `J = id`
    every hypothesis here holds and the order is one — so no exactness is
    claimed. -/
theorem sqrt_fourth_power_is_id {α : Type} (act J : α → α)
    (hJ : ∀ x, J (J x) = act x) (hinv : ∀ x, act (act x) = x) :
    ∀ x, J (J (J (J x))) = x := by
  intro x
  rw [hJ, hJ, hinv]

/-- **The square-root demand is inconsistent with generation.** On an inhabited
    carrier generated by a live act there is no `J` with `J ∘ J = act`. So
    "the fundamental act has a square root" — the algebraic seed of a complex
    structure — is inconsistent with the conjunction of inhabitance, liveness
    and generation. All three are needed: on an empty carrier there is nothing
    to contradict, and dropping liveness admits `act = J = id`. On the
    fundamental carrier all three hold, so a complex structure has to live
    somewhere the spine does not reach. -/
theorem no_sqrt_of_generated {α : Type} (act J : α → α) (z : α)
    (hl : Orbit.Live act) (hgen : TwoCycle.Generated act)
    (hJ : ∀ x, J (J x) = act x) : False := by
  rcases hgen z (J z) with h | h
  · exact hl z (by rw [← hJ z, h, h])
  · have hfix : J (act z) = act z := by rw [← h, hJ z, h]
    have hacz : act z = act (act z) := by rw [← hJ (act z), hfix, hfix]
    rcases hgen (act z) z with hz | hz
    · exact hl z hz.symm
    · exact hl z (hacz.trans hz.symm)

/-- Consistency of the square-root demand away from the fundamental: on a
    four-element carrier the quarter-turn squares to the componentwise flip,
    which is a live involution. Generation must fail there, and the last
    conjunct records that it does. -/
theorem sqrt_model_exists :
    ∃ (act J : Bool × Bool → Bool × Bool),
      (∀ x, J (J x) = act x) ∧ Orbit.Live act ∧ (∀ x, act (act x) = x) ∧
      ¬ TwoCycle.Generated act := by
  refine ⟨fun x => (!x.1, !x.2), fun x => (!x.2, x.1), ?_, ?_, ?_, ?_⟩
  · intro ⟨a, b⟩; cases a <;> cases b <;> rfl
  · intro ⟨a, b⟩; cases a <;> cases b <;>
      intro h <;> exact Bool.noConfusion (congrArg Prod.fst h)
  · intro ⟨a, b⟩; cases a <;> cases b <;> rfl
  · intro hgen
    rcases hgen (false, false) (true, false) with h | h
    · exact Bool.noConfusion (congrArg Prod.fst h)
    · exact Bool.noConfusion (congrArg Prod.snd h)

/-- A square root of a live act is itself fixed-point-free, hence also live. -/
theorem sqrt_is_live {α : Type} (act J : α → α)
    (hJ : ∀ x, J (J x) = act x) (hl : Orbit.Live act) : Orbit.Live J := by
  intro x hx
  have : J (J x) = x := by rw [hx, hx]
  exact hl x (by rw [← hJ x, this])

/-! ## Size of the carriers -/

/-- Stages of the colimit are pairwise distinct, so `Limit.LevelOmega` carries
    a copy of `Nat` and is infinite. No uniqueness is claimed: nothing here
    rules out other infinite carriers in the spine. -/
theorem omega_stage_injective :
    ∀ m n : Nat, Limit.LevelOmega.stage m = Limit.LevelOmega.stage n → m = n :=
  fun _ _ h => Limit.stage_inj h

/-- Each finite level is strictly larger than its predecessor: the namer
    `none` is new (`Ladder.none_is_new`). -/
theorem level_card_succ (k : Nat) :
    ∀ a : Ladder.Level k, (some a : Ladder.Level (k + 1)) ≠ none :=
  Ladder.none_is_new k

/-! ## Two-valued determinacy -/

/-- Every level assigns a definite Bool to every ordered pair of elements: the
    reading is total and dispersion-free. Trivial as a Lean statement — it is
    recorded because it is the classical commitment that any quantum axiom must
    displace, not because it is hard. -/
theorem reading_is_total_two_valued (k : Nat) :
    ∀ x y : Ladder.Level k,
      Ladder.rep k x y = true ∨ Ladder.rep k x y = false := by
  intro x y
  cases Ladder.rep k x y
  · exact Or.inr rfl
  · exact Or.inl rfl

/-! ## Summary -/

/-- Collected starting position: asymmetric reading, no square root of the act
    on its own carrier, an infinite colimit carrier, and total two-valued
    readings. -/
theorem starting_position :
    (∃ x y : Ladder.Level 0, Ladder.rep 0 x y ≠ Ladder.rep 0 y x) ∧
    (¬ ∃ J : Bool → Bool, ∀ b, J (J b) = Canon.theFundamental b) ∧
    (∀ m n : Nat,
      Limit.LevelOmega.stage m = Limit.LevelOmega.stage n → m = n) ∧
    (∀ k (x y : Ladder.Level k),
      Ladder.rep k x y = true ∨ Ladder.rep k x y = false) :=
  ⟨rep_not_symmetric, no_sqrt_on_fundamental, omega_stage_injective,
   reading_is_total_two_valued⟩

#print axioms Quantum.SpineFacts.rep_zero_is_first_projection
#print axioms Quantum.SpineFacts.rep_not_symmetric
#print axioms Quantum.SpineFacts.rep_not_symmetric_at
#print axioms Quantum.SpineFacts.no_sqrt_on_fundamental
#print axioms Quantum.SpineFacts.no_sqrt_of_generated
#print axioms Quantum.SpineFacts.sqrt_model_exists
#print axioms Quantum.SpineFacts.sqrt_fourth_power_is_id
#print axioms Quantum.SpineFacts.sqrt_is_live
#print axioms Quantum.SpineFacts.omega_stage_injective
#print axioms Quantum.SpineFacts.level_card_succ
#print axioms Quantum.SpineFacts.reading_is_total_two_valued
#print axioms Quantum.SpineFacts.starting_position

end Quantum.SpineFacts
