import TwoBounce

/-!
# Overtones (EXPERIMENTAL — quarantined; exports nothing to the paper)

Probe: the fundamental has period two; do higher periods arise from it?
Answer: yes, by composition of exactly two flips. The dihedral fact
(rotation = two reflections) is realised concretely on `Fin 3` and
`Fin 5`, and is now proved in general closed form: for every `n` and
every `k : Fin n`, the rotation `rot k = (· + k)` equals the mirror
through `0` (`reflZero = (-·)`) followed by the mirror through `k`
(`reflAt k = (k - ·)`), both involutions, packaged as the computable
`rotFactor k : TwoBounceFactor (rot k)`. This subsumes the concrete
exhibits: `three_from_two_flips_general` and
`five_from_two_flips_general` re-derive the `Fin 3` / `Fin 5` shapes
as instances (the original `decide` proofs are kept alongside).
Beyond rotations, every injective endomap on a finite carrier is a
composite of two involutions via the corpus's own `factor_fin` (a
computable, axiom-free orbit-traversal construction). Every finite period above the fundamental is therefore
generated by a pair of flips (the musical name is decoration, not a
claim), and for rotations the generating pair is additionally
given in closed arithmetic form rather than by orbit search. All proofs are
pointwise (no function extensionality). Nothing here asserts a
continuum and nothing here is imported by any paper-cited module.
-/
namespace Experimental.Overtones

open Bridge.TwoBounce

/-! ## Period three, concretely -/

/-- Rotation by one on `Fin 3`: the period-three overtone. -/
def cyc3 : Fin 3 → Fin 3 := fun i => i + 1

/-- Mirror through 0. -/
def refl3 : Fin 3 → Fin 3 := fun i => 0 - i

/-- Mirror through one half. -/
def refl3' : Fin 3 → Fin 3 := fun i => 1 - i

theorem refl3_involution : IsInvolution refl3 := by
  unfold IsInvolution; decide

theorem refl3'_involution : IsInvolution refl3' := by
  unfold IsInvolution; decide

/-- The period-three overtone is exactly two flips. -/
theorem three_from_two_flips : ∀ i, cyc3 i = refl3' (refl3 i) := by
  decide

/-- `cyc3` genuinely has period three: the cube is the identity and no
    smaller positive power rests anywhere. -/
theorem cyc3_period_three :
    (∀ i, cyc3 (cyc3 (cyc3 i)) = i) ∧
    (∀ i, cyc3 i ≠ i) ∧
    (∀ i, cyc3 (cyc3 i) ≠ i) := by
  decide

/-! ## Period five, concretely -/

/-- Rotation by one on `Fin 5`: a prime overtone above the fundamental. -/
def cyc5 : Fin 5 → Fin 5 := fun i => i + 1

def refl5 : Fin 5 → Fin 5 := fun i => 0 - i

def refl5' : Fin 5 → Fin 5 := fun i => 1 - i

theorem refl5_involution : IsInvolution refl5 := by
  unfold IsInvolution; decide

theorem refl5'_involution : IsInvolution refl5' := by
  unfold IsInvolution; decide

theorem five_from_two_flips : ∀ i, cyc5 i = refl5' (refl5 i) := by
  decide

theorem cyc5_period_five :
    (∀ i, cyc5 (cyc5 (cyc5 (cyc5 (cyc5 i)))) = i) ∧
    (∀ i, cyc5 i ≠ i) ∧
    (∀ i, cyc5 (cyc5 i) ≠ i) ∧
    (∀ i, cyc5 (cyc5 (cyc5 i)) ≠ i) ∧
    (∀ i, cyc5 (cyc5 (cyc5 (cyc5 i))) ≠ i) := by
  decide

/-! ## Overtone generation in general -/

/-- Every injective endomap on a finite carrier, in particular every
    n-cycle, is a composite of two involutions: the whole finite
    period spectrum lies exactly two flips above the fundamental. -/
theorem overtone_generation {n : Nat} (U : Fin n → Fin n)
    (h : EndoInj U) :
    ∃ φ σ : Fin n → Fin n,
      IsInvolution φ ∧ IsInvolution σ ∧ ∀ x, U x = σ (φ x) :=
  let F := factor_fin U h
  ⟨F.φ, F.σ, F.φ_inv, F.σ_inv, F.factor⟩

theorem cyc3_injective : EndoInj cyc3 := by
  unfold EndoInj; decide

theorem cyc5_injective : EndoInj cyc5 := by
  unfold EndoInj; decide

/-! ## The general dihedral factorisation

Closed form for every rotation on every finite carrier: `rot k` is
`reflAt k ∘ reflZero`, two explicit involutions. All identities are
proved at the `.val` level via `Fin.ext`; the `n = 0` cases are
vacuous since `Fin 0` is empty. -/

/-- Rotation by `k` on `Fin n`: the general overtone step. -/
def rot {n : Nat} (k : Fin n) : Fin n → Fin n := fun i => i + k

/-- Mirror through `0` on `Fin n` (negation). -/
def reflZero {n : Nat} : Fin n → Fin n := fun i => -i

/-- Mirror through the `k`-axis on `Fin n`: `i ↦ k - i`. -/
def reflAt {n : Nat} (k : Fin n) : Fin n → Fin n := fun i => k - i

/-- Value of negation on `Fin n`: `(-i).val = (n - i.val) % n`. -/
private theorem neg_val {n : Nat} (i : Fin n) :
    (-i).val = (n - i.val) % n := by
  rw [Fin.neg_def]

/-- `Nat` core of `reflZero_involution`: double reflection through
    `0` modulo `n` is the identity on `{0, …, n-1}`. -/
private theorem neg_neg_val (n a : Nat) (ha : a < n) :
    (n - (n - a) % n) % n = a := by
  cases Nat.eq_zero_or_pos a with
  | inl h0 =>
    subst h0
    rw [Nat.sub_zero, Nat.mod_self, Nat.sub_zero, Nat.mod_self]
  | inr hpos =>
    have h1 : (n - a) % n = n - a := Nat.mod_eq_of_lt (by omega)
    rw [h1]
    have h2 : n - (n - a) = a := by omega
    rw [h2]
    exact Nat.mod_eq_of_lt ha

/-- `Nat` core of `reflAt_involution`: double reflection through the
    `b`-axis modulo `n` is the identity on `{0, …, n-1}`. -/
private theorem sub_sub_val (n a b : Nat) (ha : a < n) (hb : b < n) :
    (n - (n - a + b) % n + b) % n = a := by
  cases Nat.lt_or_ge b a with
  | inl hba =>
    have h1 : (n - a + b) % n = n - a + b := Nat.mod_eq_of_lt (by omega)
    rw [h1]
    have h2 : n - (n - a + b) + b = a := by omega
    rw [h2]
    exact Nat.mod_eq_of_lt ha
  | inr hab =>
    have h1 : n - a + b = b - a + n := by omega
    rw [h1, Nat.add_mod_right]
    have h2 : (b - a) % n = b - a := Nat.mod_eq_of_lt (by omega)
    rw [h2]
    have h3 : n - (b - a) + b = a + n := by omega
    rw [h3, Nat.add_mod_right]
    exact Nat.mod_eq_of_lt ha

/-- `Nat` core of the dihedral identity: reflect through `0`, reflect
    through `b`, and the net effect is addition of `b` modulo `n`. -/
private theorem dihedral_val (n a b : Nat) (ha : a < n) :
    (n - (n - a) % n + b) % n = (a + b) % n := by
  cases Nat.eq_zero_or_pos a with
  | inl h0 =>
    subst h0
    rw [Nat.sub_zero, Nat.mod_self, Nat.sub_zero, Nat.zero_add]
    exact Nat.add_mod_left n b
  | inr hpos =>
    have h1 : (n - a) % n = n - a := Nat.mod_eq_of_lt (by omega)
    rw [h1]
    have h2 : n - (n - a) = a := by omega
    rw [h2]

/-- The zero-axis mirror is an involution on every finite carrier. -/
theorem reflZero_involution {n : Nat} :
    IsInvolution (reflZero (n := n)) := by
  intro i
  apply Fin.ext
  show (-(-i)).val = i.val
  rw [neg_val, neg_val]
  exact neg_neg_val n i.val i.isLt

/-- The `k`-axis mirror is an involution for every `k` and `n`. -/
theorem reflAt_involution {n : Nat} (k : Fin n) :
    IsInvolution (reflAt k) := by
  intro i
  apply Fin.ext
  show (k - (k - i)).val = i.val
  rw [Fin.val_sub, Fin.val_sub]
  exact sub_sub_val n i.val k.val i.isLt k.isLt

/-- **The dihedral identity in closed form.** On every `Fin n`,
    rotation by `k` is the mirror through `0` followed by the mirror
    through `k`: `i + k = k - (-i)`, pointwise. -/
theorem rot_eq_two_flips {n : Nat} (k : Fin n) :
    ∀ i, rot k i = reflAt k (reflZero i) := by
  intro i
  apply Fin.ext
  show (i + k).val = (k - (-i)).val
  rw [Fin.val_add, Fin.val_sub, neg_val]
  exact (dihedral_val n i.val k.val i.isLt).symm

/-- Fully explicit two-bounce factorisation of the rotation by `k`
    on `Fin n`. Contrast with the corpus's `factor_fin`, which is
    also computable but constructs its involution pair by orbit
    traversal for arbitrary injections: here the pair is given by
    closed-form arithmetic mirrors (`reflZero`, `reflAt k`) for
    every rotation on every finite carrier. -/
def rotFactor {n : Nat} (k : Fin n) : TwoBounceFactor (rot k) where
  φ := reflZero
  σ := reflAt k
  φ_inv := reflZero_involution
  σ_inv := reflAt_involution k
  factor := rot_eq_two_flips k

/-- Existence form of the closed-form factorisation: the shape of
    `overtone_generation`, but with the pair given in closed form
    rather than by the orbit-traversal construction of
    `factor_fin`. -/
theorem rot_from_two_flips {n : Nat} (k : Fin n) :
    ∃ φ σ : Fin n → Fin n,
      IsInvolution φ ∧ IsInvolution σ ∧ ∀ x, rot k x = σ (φ x) :=
  ⟨reflZero, reflAt k, reflZero_involution, reflAt_involution k,
   rot_eq_two_flips k⟩

/-! ## Subsumption of the concrete exhibits

The `Fin 3` / `Fin 5` shapes re-derived as instances of the general
theorem. The original `decide` proofs above are kept intact; only the
bridge `0 - i = -i` (a `Nat.zero_mod` computation) separates the
concrete mirrors from the general ones. -/

/-- On a nonempty carrier the literal-`0` mirror `0 - i` agrees with
    the negation mirror `reflZero`. -/
private theorem zero_sub_eq_neg {m : Nat} (i : Fin (m + 1)) :
    (0 : Fin (m + 1)) - i = -i := by
  apply Fin.ext
  rw [Fin.val_sub, neg_val]
  show (m + 1 - i.val + 0) % (m + 1) = (m + 1 - i.val) % (m + 1)
  rw [Nat.add_zero]

/-- `three_from_two_flips`, re-derived from `rot_eq_two_flips` at
    `n = 3`, `k = 1` (subsumption of the concrete exhibit). -/
theorem three_from_two_flips_general :
    ∀ i, cyc3 i = refl3' (refl3 i) := by
  intro i
  have hz : refl3 i = reflZero i := zero_sub_eq_neg i
  rw [hz]
  exact rot_eq_two_flips (1 : Fin 3) i

/-- `five_from_two_flips`, re-derived from `rot_eq_two_flips` at
    `n = 5`, `k = 1` (subsumption of the concrete exhibit). -/
theorem five_from_two_flips_general :
    ∀ i, cyc5 i = refl5' (refl5 i) := by
  intro i
  have hz : refl5 i = reflZero i := zero_sub_eq_neg i
  rw [hz]
  exact rot_eq_two_flips (1 : Fin 5) i

/-- Closed-form factor for the period-three overtone: `rotFactor` at
    `k = 1` on `Fin 3` (`cyc3` is definitionally `rot 1`). -/
def cyc3Factor : TwoBounceFactor cyc3 := rotFactor (1 : Fin 3)

/-- Closed-form factor for the period-five overtone: `rotFactor` at
    `k = 1` on `Fin 5` (`cyc5` is definitionally `rot 1`). -/
def cyc5Factor : TwoBounceFactor cyc5 := rotFactor (1 : Fin 5)

#print axioms Experimental.Overtones.refl3_involution
#print axioms Experimental.Overtones.refl3'_involution
#print axioms Experimental.Overtones.three_from_two_flips
#print axioms Experimental.Overtones.cyc3_period_three
#print axioms Experimental.Overtones.refl5_involution
#print axioms Experimental.Overtones.refl5'_involution
#print axioms Experimental.Overtones.five_from_two_flips
#print axioms Experimental.Overtones.cyc5_period_five
#print axioms Experimental.Overtones.overtone_generation
#print axioms Experimental.Overtones.cyc3_injective
#print axioms Experimental.Overtones.cyc5_injective
#print axioms Experimental.Overtones.neg_val
#print axioms Experimental.Overtones.neg_neg_val
#print axioms Experimental.Overtones.sub_sub_val
#print axioms Experimental.Overtones.dihedral_val
#print axioms Experimental.Overtones.reflZero_involution
#print axioms Experimental.Overtones.reflAt_involution
#print axioms Experimental.Overtones.rot_eq_two_flips
#print axioms Experimental.Overtones.rotFactor
#print axioms Experimental.Overtones.rot_from_two_flips
#print axioms Experimental.Overtones.zero_sub_eq_neg
#print axioms Experimental.Overtones.three_from_two_flips_general
#print axioms Experimental.Overtones.five_from_two_flips_general
#print axioms Experimental.Overtones.cyc3Factor
#print axioms Experimental.Overtones.cyc5Factor

end Experimental.Overtones
